tproxy-port: 7893
bind-address: "*"
mode: rule
allow-lan: true
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
unified-delay: true
ipv6: false
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.0/8
  use-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query
proxies:
  - name: sg1 443
    server: ruangguru.com
    port: 443
    type: vmess
    uuid: a9481600-ef36-402a-a0e5-5547bfd7b87c
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg-ovh2.v2-ray.com
    network: ws
    ws-opts:
      path: /fastssh/konqwe/627a57632b590/
      headers:
        Host: sg-ovh2.v2-ray.com
    udp: true
  - name: sg2 80
    server: ruangguru.com
    port: 80
    type: vmess
    uuid: a9481600-ef36-402a-a0e5-5547bfd7b87c
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg-ovh2.v2-ray.com
    network: ws
    ws-opts:
      path: /fastssh/konqwe/627a57632b590/
      headers:
        Host: sg-ovh2.v2-ray.com
    udp: true
  - name: id1 443
    server: ruangguru.com
    port: 443
    type: vmess
    uuid: dbcbccc9-75bd-4d10-ae40-f98d5f7fc2c7
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id3.v2-ray.com
    network: ws
    ws-opts:
      path: /fastssh/qwep/627a57d2968ea/
      headers:
        Host: id3.v2-ray.com
    udp: true
  - name: id2 80
    server: ruangguru.com
    port: 80
    type: vmess
    uuid: dbcbccc9-75bd-4d10-ae40-f98d5f7fc2c7
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id3.v2-ray.com
    network: ws
    ws-opts:
      path: /fastssh/qwep/627a57d2968ea/
      headers:
        Host: id3.v2-ray.com
    udp: true
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - sg1 443
      - sg2 80
      - id1 443
      - id2 80
      - DIRECT
  - name: BEST-PING
    type: url-test
    url: http://hi.bonds.id/ping
    interval: 300
    tolerance: 50
    proxies:
      - sg1 443
      - sg2 80
      - id1 443
      - id2 80          
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY
