
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
ipv6: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
  fallback:
    - tcp://1.1.1.1
    - tcp://8.8.8.8
    - 1.1.1.1
    - 8.8.8.8
tun:
  enable: true
  stack: system 
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://8.8.8.8:53
experimental:
  interface-name: en0

proxies:
  - {name: SG Trojan OVH Line, server: sgovh-trojan.bonds.id, port: 443, udp: true, type: trojan, password: 8a619070-d335-11ec-b03f-1239d0255272, sni: cdntest40.line-scdn.net, skip-cert-verify: true}
  - {name: ID Rackh Trojan Line, server: id-rackhtj.bonds.id, port: 443, udp: true, type: trojan, password: dcfac860-d335-11ec-b328-1239d0255272, sni: cdntest40.line-scdn.net, skip-cert-verify: true}
  - {name: w11-trojan.bonds.id Line, server: w11-trojan.bonds.id, port: 443, udp: true, type: trojan, password: 2b1edb00-d336-11ec-8a02-1239d0255272, sni: cdntest40.line-scdn.net, skip-cert-verify: true}
  - {name: w12-trojan.bonds.id Grab, server: w12-trojan.bonds.id, port: 443, udp: true, type: trojan, password: 6e773230-d336-11ec-b685-1239d0255272, sni: zendesk1.grab.com, skip-cert-verify: true}
  - {name: w11-trojan.bonds.id Line90, server: w11-trojan.bonds.id, port: 443, udp: true, type: trojan, password: 9a5e3cf0-d336-11ec-80eb-1239d0255272, sni: cdntest40.line-scdn.net, skip-cert-verify: true}
  - {name: w13-trojan.bonds.id grab, server: w13-trojan.bonds.id, port: 443, udp: true, type: trojan, password: d5a931a0-d336-11ec-8c98-1239d0255272, sni: zendesk1.grab.com.net, skip-cert-verify: true}

proxy-groups:
  - name: howdy-trojan
    type: select
    proxies:
      - SG Trojan OVH Line
      - ID Rackh Trojan Line
      - w11-trojan.bonds.id Line
      - w12-trojan.bonds.id Grab
      - w11-trojan.bonds.id Line90
      - w13-trojan.bonds.id grab
rule-providers:
  clash:
    type: http
    behavior: domain
    url: https://howdy.id/download/rules/clash.txt
    path: ./providers/rule-provider_clash.yaml
    interval: 86400
rules:
 - MATCH,howdy-trojan