# UPLOAD BY ARYA CHANNEL99
# UDANAWU BLITAR JATIM
port: 7890
socks-port: 7891
mixed-port: 10809
mode: global
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret : ""
bind-address: "*"
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7894
  use-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - 1.1.1.1
  fallback:
    - https://dns.google/dns-query
proxies:
  - name: Line
    server: cdntest40.line-scdn.net
    port: 443
    type: vmess
    uuid: 62987351-9838-45fe-b7fa-a16a7763cc7b
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dynamic-sg1b.obfs.xyz
    network: ws
    ws-opts:
      path: /fastssh
      headers:
        Host: dynamic-sg1b.obfs.xyz
    udp: true
  - name: Grab
    server: zendesk1.grab.com
    port: 443
    type: vmess
    uuid: 1995f148-3f65-44c1-95c3-8dcdbd971869
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dynamic-sg1b.obfs.xyz
    network: ws
    ws-opts:
      path: /fastssh
      headers:
        Host: dynamic-sg1b.obfs.xyz
    udp: true    
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - Line
      - Grab
      - DIRECT
  - name: BEST-PING
    type: url-test
    url: http://hi.bonds.id/ping
    interval: 300
    tolerance: 50
    proxies:
      - Line
      - Grab     
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY
