port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
  fallback:
    - 1.0.0.1
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - 112.215.37.165
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 112.215.37.165
proxies:
 #vmessgrpc
  - name: Aneid-serverssh.net LINE
    server: cdntest40.line-scdn.net
    port: 443
    type: vmess
    uuid: c4f96e86-ffaa-4908-b59b-1061388f28bb
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg1grpc.serverssh.us
    network: grpc
    grpc-opts:
      grpc-service-name: grpc
    udp: true
  - name: Aneid-serverssh.net GRAB
    server: zendesk1.grab.com
    port: 443
    type: vmess
    uuid: c4f96e86-ffaa-4908-b59b-1061388f28bb
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg1grpc.serverssh.us
    network: grpc
    grpc-opts:
      grpc-service-name: grpc
    udp: true 
 #vlessgrcp     
  - name: sg1.vless.co LINE
    server: cdntest40.line-scdn.net
    port: 80
    type: vless
    uuid: 81f1f510-3ca7-4734-8956-0f4fce670af5
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg1.vless.co
    network: ws
    ws-opts:
      path: /fastssh/taqimeww/628061bc527fd/
      headers:
        Host: sg1.vless.co
    udp: true
  - name: sg1.vless.co LINE2 
    server: cdntest40.line-scdn.net
    port: 443
    type: vless
    uuid: 81f1f510-3ca7-4734-8956-0f4fce670af5
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg1.vless.co
    network: ws
    ws-opts:
      path: /fastssh/taqimeww/628061bc527fd/
      headers:
        Host: sg1.vless.co
    udp: true
  - name: sg1.vless.co GRAB
    server: zendesk1.grab.com
    port: 80
    type: vless
    uuid: 81f1f510-3ca7-4734-8956-0f4fce670af5
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg1.vless.co
    network: ws
    ws-opts:
      path: /fastssh/taqimeww/628061bc527fd/
      headers:
        Host: sg1.vless.co
    udp: true
  - name: sg1.vless.co GRAB2
    server: zendesk1.grab.com
    port: 443
    type: vless
    uuid: 81f1f510-3ca7-4734-8956-0f4fce670af5
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg1.vless.co
    network: ws
    ws-opts:
      path: /fastssh/taqimeww/628061bc527fd/
      headers:
        Host: sg1.vless.co
    udp: true
 #trojango  
  - name: SG OVH LINE
    server: cdntest40.line-scdn.net
    port: 443
    type: trojan
    password: 97aa3c80-d3f5-11ec-a91e-1239d0255272
    skip-cert-verify: true
    sni: sgovh-trojan.bonds.id
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sgovh-trojan.bonds.id
    udp: true
  - name: SG OVH LINE2
    server: cdntest40.line-scdn.net
    port: 443
    type: trojan
    password: 97aa3c80-d3f5-11ec-a91e-1239d0255272
    skip-cert-verify: true
    sni: sgovh-trojan.bonds.id
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sgovh-trojan.bonds.id
    udp: true
  - name: SG OVH GRAB
    server: zendesk1.grab.com
    port: 443
    type: trojan
    password: 97aa3c80-d3f5-11ec-a91e-1239d0255272
    skip-cert-verify: true
    sni: sgovh-trojan.bonds.id
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sgovh-trojan.bonds.id
    udp: true
  - name: SG OVH GRAB2
    server: zendesk1.grab.com
    port: 443
    type: trojan
    password: 97aa3c80-d3f5-11ec-a91e-1239d0255272
    skip-cert-verify: true
    sni: sgovh-trojan.bonds.id
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sgovh-trojan.bonds.id
    udp: true
 #trojangrpc 
  - name: sshocean-wsded_Trojan_gRPC LINE
    server: cdntest40.line-scdn.net
    port: 8433
    type: trojan
    password: fd35f8db-9df0-46fb-8976-f3e9af4ddd6c
    skip-cert-verify: true
    sni: sgt1.sshocean.net
    network: grpc
    grpc-opts:
      grpc-service-name: grpc
    udp: true
  - name: sshocean-wsded_Trojan_gRPC GRAB
    server: zendesk1.grab.com
    port: 8433
    type: trojan
    password: fd35f8db-9df0-46fb-8976-f3e9af4ddd6c
    skip-cert-verify: true
    sni: sgt1.sshocean.net
    network: grpc
    grpc-opts:
      grpc-service-name: grpc
    udp: true
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - Aneid-serverssh.net LINE
      - Aneid-serverssh.net GRAB
      - sg1.vless.co LINE
      - sg1.vless.co LINE2
      - sg1.vless.co GRAB
      - sg1.vless.co GRAB2
      - SG OVH LINE
      - SG OVH LINE2
      - SG OVH GRAB
      - SG OVH GRAB2
      - sshocean-wsded_Trojan_gRPC LINE
      - sshocean-wsded_Trojan_gRPC GRAB
      - BEST-PING
      - DIRECT
  - name: BEST-PING
    type: url-test
    url: http://hi.bonds.id/ping
    interval: 300
    tolerance: 50
    proxies: 
      - Aneid-serverssh.net LINE
      - Aneid-serverssh.net GRAB
      - sg1.vless.co LINE
      - sg1.vless.co LINE2
      - sg1.vless.co GRAB
      - sg1.vless.co GRAB2
      - SG OVH LINE
      - SG OVH LINE2
      - SG OVH GRAB
      - SG OVH GRAB2
      - sshocean-wsded_Trojan_gRPC LINE
      - sshocean-wsded_Trojan_gRPC GRAB         
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY
