port: 7890
socks-port: 7891
mixed-port: 10809
mode: global
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret : ""
bind-address: "*"
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7894
  use-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - 1.1.1.1
  fallback:
    - https://dns.google/dns-query
proxies:
  - name: BUG GRAB
    server: zendesk1.grab.com
    port: 443
    type: trojan
    password: e3f52fb0-d27f-11ec-8833-1239d0255272
    skip-cert-verify: true
    sni: idtj-uninet.bonds.id
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: idtj-uninet.bonds.id
    udp: true
  - name: BUG LINE
    server: cdntest40.line-scdn.net
    port: 443
    type: trojan
    password: 5083cde0-d28c-11ec-9672-1239d0255272
    skip-cert-verify: true
    sni: sg8-trojan.bonds.id
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg8-trojan.bonds.id
    udp: true
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - BUG GRAB
      - BUG LINE
      - BEST-PING
      - DIRECT
  - name: BEST-PING
    type: url-test
    url: http://hi.bonds.id/ping
    interval: 300
    tolerance: 50
    proxies:
      - BUG GRAB
      - BUG LINE
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY